name: Other
description: Other issue
projects: ['FlashDrag/11']
body:
- type: textarea
  attributes:
    label: "Issue Description:"
- type: markdown
  attributes:
    value: "Thanks for contributing to the CycleBay!"




