# Generated by Django 5.2 on 2025-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.CharField(default='lifetime'),
        ),
    ]
