# Generated by Django 5.2 on 2025-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.CharField(default='1'),
        ),
    ]
